Skip time check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,14 +13,14 @@ jobs:
     timeout-minutes: 5
     
     steps:
-    - name: Check Time Window
-      # Check if current time is between 6 PM and midnight AEDT
-      run: |
-        current_hour=$(TZ='Australia/Sydney' date +%H)
-        if [ $current_hour -lt 18 ] || [ $current_hour -ge 24 ]; then
-          echo "Outside of target time window (6 PM to midnight AEDT)"
-          exit 78  # Neutral exit code to skip the job
-        fi
+    # - name: Check Time Window
+    #   # Check if current time is between 6 PM and midnight AEDT
+    #   run: |
+    #     current_hour=$(TZ='Australia/Sydney' date +%H)
+    #     if [ $current_hour -lt 18 ] || [ $current_hour -ge 24 ]; then
+    #       echo "Outside of target time window (6 PM to midnight AEDT)"
+    #       exit 78  # Neutral exit code to skip the job
+    #     fi
     
     - name: Checkout repository
       uses: actions/checkout@v4
